models/store.py
import re
import uuid
from dataclasses import dataclass, field
from typing import Dict
from models.model import Model


@dataclass
class Store(Model):
    collection: str = field(init=False, default='stores')
    name: str
    url_prefix: str
    tag_name: str
    query: Dict
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def json(self):
        return {
            "_id": self._id,
            "name": self.name,
            "url_prefix": self.url_prefix,
            "tag_name": self.tag_name,
            "query": self.query
        }

    @classmethod
    def get_by_name(cls, store_name: str) -> "Store":
        # Store.get_by_name("John Lewis")
        return cls.find_one_by("name", store_name)

    @classmethod
    def get_by_url_prefix(cls, url_prefix: str) -> "Store":
        # Store.get_by_url_prefix("https://www.johnlewis.com/")
        url_regex = {"$regex": "^{}".format(url_prefix)}
        return cls.find_one_by("url_prefix", url_regex)

    @classmethod
    def find_by_url(cls, url: str) -> "Store":
        """
        takes item url and return a store
        """
        pattern = re.compile(r"https?://.*?/")
        match = pattern.search(url)
        url_prefix = match.group(0)
        return cls.get_by_url_prefix(url_prefix)

views/stores.py
import json
from flask import Blueprint, render_template, request, url_for, redirect
from models.store import Store
from models.user import requires_admin, requires_login

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
@requires_login
def index():
    stores = Store.all()
    return render_template('stores/index.html', stores=stores)


@store_blueprint.route('/new', methods=['GET', 'POST'])
@requires_admin
def new_store():
    if request.method == 'POST':
        store_name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(store_name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        store.url_prefix = request.form['url_prefix']
        store.tag_name = request.form['tag_name']
        print(request.form['query'])
        print(type(request.form['query']))
        store.query = json.loads(request.form['query'])
        store.save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('stores/edit_store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@requires_admin
def delete_store(store_id):
    Store.get_by_id(store_id).remove_from_mongo()
    return redirect(url_for('.index'))

templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Edit Store</h1></header>
    <section class="edit-store-form">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="John Lewis" value="{{ store.name }}" disabled/>
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://www.johnlewis.com"
                       value="{{ store.url_prefix }}"
                       aria-describedby="urlPrefixHelp"/>
                <small id="urlPrefixHelp" class="form-text text-muted">What is the common part of all URLs for this store?</small>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span"
                       value="{{ store.tag_name }}" aria-describedby="tagNameHelp"/>
                <small id="tagNameHelp" class="form-text text-muted">What HTML tag contains the price information for items in this store?</small>
            </div>
<!--            <div class="form-group">-->
<!--                <label for="query">Query</label>-->
<!--                <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price&#45;&#45;large"}'-->
<!--                       value="{{ store.query|tojson|safe }}" aria-describedby="queryHelp"/>-->
<!--                <small id="queryHelp" class="form-text text-muted">What query should be used to uniquely identify the price? Must be double quoted. </small>-->
<!--            </div>-->
            <div class="form-group">
                <label for="query">Query</label>
                <textarea  type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price--large"}'
                            aria-describedby="queryHelp"/>{{ store.query|tojson|safe }}</textarea>
                <small id="queryHelp" class="form-text text-muted">What query should be used to uniquely identify the price? Must be double quoted. </small>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </section>
{% endblock %}

templates/stores/index.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Store</h1></header>
    <section>
        <div class="list-group mb-3">
            {% for store in stores %}

                <div class="list-group-item">
                    <h4>{{ store.name }}</h4>
                    <p>
                        <a href="{{ store.url_prefix }}">{{ store.url_prefix }}</a>
                    </p>
                    {% if session['email'] == config.ADMIN %}
<!--                  hiding the button is not sufficient also need reauries_admin decorator for stores/new and stores/edit and stores/delete  h-->
                    <a class="btn btn-secondary" href="{{ url_for('stores.edit_store', store_id=store._id) }}">
                        Edit
                    </a>
                    <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}">
                        Permanently delete store
                    </a>
                    {% endif %}
                </div>

            {% endfor %}
        </div>
        {% if session['email'] == config.ADMIN %}
        <a class="btn btn-primary" href="{{ url_for('stores.new_store') }}">
            Create new
        </a>
        {% endif %}
    </section>
{% endblock %}

templates/stores/new_store.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Create Store</h1></header>
    <section class="create-store-form">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="John Lewis"/>
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="https://www.johnlewis.com/" aria-describedby="urlPrefixHelp"/>
                <small id="urlPrefixHelp" class="form-text text-muted">What is the common part of all URLs for this store?</small>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp"/>
                <small id="tagNameHelp" class="form-text text-muted">What HTML tag contains the price information for items in this store?</small>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"class": "price price--large"}' aria-describedby="queryHelp"/>
                <small id="queryHelp" class="form-text text-muted">What query should be used to uniquely identify the price? Must be double quoted. </small>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </section>
{% endblock %}